# Netlify configuration for Angular PWA with optimal caching and updates

[build]
  # Build command for Angular
  command = "cd frontend/pickleball-app && npm ci && npm run build"
  # Build output directory
  publish = "frontend/pickleball-app/dist/pickleball-app/"

# Cache headers for optimal PWA performance and updates
[[headers]]
  # Index.html should never be cached to ensure updates are detected
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  # Service worker should never be cached
  for = "/ngsw-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  # Service worker config should never be cached
  for = "/ngsw.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  # Web app manifest should have short cache
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  # JavaScript and CSS files with hashes can be cached long-term
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Assets (images, fonts) can be cached long-term
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Font files
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules for Angular routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "editor"], Country = ["!US"]}

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# PWA specific headers
[[headers]]
  for = "/*.html"
  [headers.values]
    # Service Worker registration scope
    Service-Worker-Allowed = "/"